version: '2'
services:
  fluentd:
    image: quay.io/${project.groupId}/elkf4dev-fluentd:${project.version}
    volumes:
      - ${PWD}/conf/fluentd.conf:/fluentd/etc/fluent.conf
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch