language: java

jdk:
  - openjdk8

sudo: required

services:
  - docker

install: true # This runs the "true" command in the install phase; thus skipping install

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push quay.io/com.jeecookbook.elkf4dev/elkf4dev-fluentd:latest;
    fi

cache:
  directories:
    - $HOME/.m2/repository/
