language: java

jdk:
  - openjdk8

sudo: required

services:
  - docker

script: mvn clean install

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io;
    docker push quay.io/elkf4dev-fluentd:latest;
    fi

cache:
  directories:
    - $HOME/.m2/repository/
