language: java

jdk:
  - openjdk8

sudo: required

services:
  - docker

install: true # This runs the "true" command in the install phase; thus skipping install

script:

cache:
  directories:
    - $HOME/.m2/repository/