language: java

jdk:
  - openjdk8

sudo: required

services:
  - docker

script: mvn clean install

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag com.jeecookbook.elkf4dev/elkf4dev-fluentd:latest quay.io/com.jeecookbook.elkf4dev/elkf4dev-fluentd:latest;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io;
    docker push quay.io/${DOCKER_USERNAME}/com.jeecookbook.elkf4dev-fluentd:latest;
    fi

cache:
  directories:
    - $HOME/.m2/repository/
